model_config:
  model_name: "gpt2"
  device: "cuda"
  max_length: 2048
  batch_size: 4
  cache_size: 1000
  temperature: 0.7
  top_p: 0.9
  streaming: false
  timeout: 30
  
vector_store:
  type: "sqlite"
  db_path: "./data/vectors.db"
  settings:
    chunk_size: 512
    similarity_threshold: 0.7
    max_results: 5
    connection_timeout: 30

agents:
  max_concurrent: 5
  timeout: 300